language: php

php:
  - 7.0
  - 7.1

before_install:
  - sudo apt-get update
  - sudo apt-get install sqlite3

before_script:
  - travis_retry composer self-update
  - travis_retry composer update --prefer-dist --no-interaction --prefer-stable

script:
  - vendor/bin/phpunit --debug -c phpunit.xml.dist